# Generated by Django 2.1 on 2018-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(null=True)),
                ('data_format', models.CharField(max_length=20, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('year_completed', models.IntegerField(null=True)),
                ('clue_small_area', models.CharField(max_length=30, null=True)),
                ('clue_block', models.FloatField(null=True)),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('floors_above', models.FloatField(null=True)),
                ('resi_dwellings', models.FloatField(null=True)),
                ('studio_dwe', models.FloatField(null=True)),
                ('one_bdrm_dwe', models.FloatField(null=True)),
                ('two_bdrm_dwe', models.FloatField(null=True)),
                ('three_bdrm_dwe', models.FloatField(null=True)),
                ('student_apartments', models.FloatField(null=True)),
                ('student_beds', models.FloatField(null=True)),
                ('student_accommodation_units', models.FloatField(null=True)),
                ('intitutional_accom_beds', models.FloatField(null=True)),
                ('hotel_rooms', models.FloatField(null=True)),
                ('serviced_apartments', models.FloatField(null=True)),
                ('hotels_serviced_apartments', models.FloatField(null=True)),
                ('hostel_beds', models.FloatField(null=True)),
                ('childcare_places', models.FloatField(null=True)),
                ('office_flr', models.FloatField(null=True)),
                ('retail_flr', models.FloatField(null=True)),
                ('industrial_flr', models.FloatField(null=True)),
                ('storage_flr', models.FloatField(null=True)),
                ('education_flr', models.FloatField(null=True)),
                ('hospital_flr', models.FloatField(null=True)),
                ('recreation_flr', models.FloatField(null=True)),
                ('publicdispaly_flr', models.FloatField(null=True)),
                ('community_flr', models.FloatField(null=True)),
                ('car_spaces', models.FloatField(null=True)),
                ('bike_spaces', models.FloatField(null=True)),
                ('town_planning_application_no', models.CharField(max_length=20, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
