# Generated by Django 2.1 on 2018-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionviz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='town_planning_application_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
