# Generated by Django 2.1 on 2018-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionviz', '0002_auto_20180825_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construction',
            old_name='Location',
            new_name='Lattitude',
        ),
        migrations.AddField(
            model_name='construction',
            name='Longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
